# Generated from the official OmniVoice docs/lang_id_name_map.tsv.
LANGUAGES = (
    ('aae', 'Arbëreshë Albanian', 'aae'),
    ('aal', 'Afade', 'aal'),
    ('aao', 'Algerian Saharan Arabic', 'aao'),
    ('ab', 'Abkhazian', 'abk'),
    ('abb', 'Bankon', 'abb'),
    ('abn', 'Abua', 'abn'),
    ('abr', 'Abron', 'abr'),
    ('abs', 'Ambonese Malay', 'abs'),
    ('abv', 'Baharna Arabic', 'abv'),
    ('acm', 'Mesopotamian Arabic', 'acm'),
    ('acw', 'Hijazi Arabic', 'acw'),
    ('acx', 'Omani Arabic', 'acx'),
    ('adf', 'Dhofari Arabic', 'adf'),
    ('adx', 'Amdo Tibetan', 'adx'),
    ('ady', 'Adyghe', 'ady'),
    ('aeb', 'Tunisian Arabic', 'aeb'),
    ('aec', 'Saidi Arabic', 'aec'),
    ('af', 'Afrikaans', 'afr'),
    ('afb', 'Gulf Arabic', 'afb'),
    ('afo', 'Eloyi', 'afo'),
    ('ahl', 'Igo', 'ahl'),
    ('ahs', 'Ashe', 'ahs'),
    ('ajg', 'Aja (Benin)', 'ajg'),
    ('aju', 'Judeo-Moroccan Arabic', 'aju'),
    ('ala', 'Alago', 'ala'),
    ('aln', 'Gheg Albanian', 'aln'),
    ('alo', 'Larike-Wakasihu', 'alo'),
    ('am', 'Amharic', 'amh'),
    ('amu', 'Guerrero Amuzgo', 'amu'),
    ('an', 'Aragonese', 'arg'),
    ('anc', 'Ngas', 'anc'),
    ('ank', 'Goemai', 'ank'),
    ('anp', 'Angika', 'anp'),
    ('anw', 'Anaang', 'anw'),
    ('aom', 'Ömie', 'aom'),
    ('apc', 'Levantine Arabic', 'apc'),
    ('apd', 'Sudanese Arabic', 'apd'),
    ('arb', 'Standard Arabic', 'arb'),
    ('arq', 'Algerian Arabic', 'arq'),
    ('ars', 'Najdi Arabic', 'ars'),
    ('ary', 'Moroccan Arabic', 'ary'),
    ('arz', 'Egyptian Arabic', 'arz'),
    ('as', 'Assamese', 'asm'),
    ('ast', 'Asturian', 'ast'),
    ('avl', 'Eastern Egyptian Bedawi Arabic', 'avl'),
    ('awo', 'Awak', 'awo'),
    ('ayl', 'Libyan Arabic', 'ayl'),
    ('ayp', 'North Mesopotamian Arabic', 'ayp'),
    ('az', 'Azerbaijani', 'aze'),
    ('ba', 'Bashkir', 'bak'),
    ('bag', 'Tuki', 'bag'),
    ('bas', 'Basa (Cameroon)', 'bas'),
    ('bax', 'Bamun', 'bax'),
    ('bba', 'Baatonum', 'bba'),
    ('bbj', "Ghomálá'", 'bbj'),
    ('bbl', 'Bats', 'bbl'),
    ('bbu', 'Kulung (Nigeria)', 'bbu'),
    ('bce', 'Bamenyam', 'bce'),
    ('bci', 'Baoulé', 'bci'),
    ('bcs', 'Kohumono', 'bcs'),
    ('bcy', 'Bacama', 'bcy'),
    ('bda', 'Bayot', 'bda'),
    ('bde', 'Bade', 'bde'),
    ('bdm', 'Buduma', 'bdm'),
    ('be', 'Belarusian', 'bel'),
    ('beb', 'Bebele', 'beb'),
    ('bew', 'Betawi', 'bew'),
    ('bfd', 'Bafut', 'bfd'),
    ('bft', 'Balti', 'bft'),
    ('bg', 'Bulgarian', 'bul'),
    ('bgp', 'Eastern Balochi', 'bgp'),
    ('bhb', 'Bhili', 'bhb'),
    ('bhh', 'Bukharic', 'bhh'),
    ('bho', 'Bhojpuri', 'bho'),
    ('bhp', 'Bima', 'bhp'),
    ('bhr', 'Bara Malagasy', 'bhr'),
    ('bjj', 'Kanauji', 'bjj'),
    ('bjk', 'Barok', 'bjk'),
    ('bjn', 'Banjar', 'bjn'),
    ('bjt', 'Balanta-Ganja', 'bjt'),
    ('bkh', 'Bakoko', 'bkh'),
    ('bkm', 'Kom (Cameroon)', 'bkm'),
    ('bky', 'Bokyi', 'bky'),
    ('bmm', 'Northern Betsimisaraka Malagasy', 'bmm'),
    ('bmq', 'Bomu', 'bmq'),
    ('bn', 'Bengali', 'ben'),
    ('bnm', 'Batanga', 'bnm'),
    ('bnn', 'Bunun', 'bnn'),
    ('bns', 'Bundeli', 'bns'),
    ('bo', 'Tibetan', 'bod'),
    ('bou', 'Bondei', 'bou'),
    ('bqg', 'Bago-Kusuntu', 'bqg'),
    ('br', 'Breton', 'bre'),
    ('bra', 'Braj', 'bra'),
    ('brh', 'Brahui', 'brh'),
    ('bri', 'Mokpwe', 'bri'),
    ('brx', 'Bodo', 'brx'),
    ('bs', 'Bosnian', 'bos'),
    ('bsh', 'Kati', 'bsh'),
    ('bsj', 'Bangwinji', 'bsj'),
    ('bsk', 'Burushaski', 'bsk'),
    ('btm', 'Batak Mandailing', 'btm'),
    ('btv', 'Bateri', 'btv'),
    ('bug', 'Buginese', 'bug'),
    ('bum', 'Bulu (Cameroon)', 'bum'),
    ('buo', 'Terei', 'buo'),
    ('bux', 'Boghom', 'bux'),
    ('bwr', 'Bura-Pabir', 'bwr'),
    ('bxf', 'Bilur', 'bxf'),
    ('byc', 'Ubaghara', 'byc'),
    ('bys', 'Burak', 'bys'),
    ('byv', 'Medumba', 'byv'),
    ('byx', 'Qaqet', 'byx'),
    ('bzc', 'Southern Betsimisaraka Malagasy', 'bzc'),
    ('bzw', 'Basa (Nigeria)', 'bzw'),
    ('ca', 'Catalan', 'cat'),
    ('ccg', 'Samba Daka', 'ccg'),
    ('ceb', 'Cebuano', 'ceb'),
    ('cen', 'Cen', 'cen'),
    ('cfa', 'Dijim-Bwilim', 'cfa'),
    ('cgg', 'Chiga', 'cgg'),
    ('chq', 'Quiotepec Chinantec', 'chq'),
    ('cjk', 'Chokwe', 'cjk'),
    ('ckb', 'Central Kurdish', 'ckb'),
    ('ckl', 'Cibak', 'ckl'),
    ('ckr', 'Kairak', 'ckr'),
    ('cky', 'Cakfem-Mushere', 'cky'),
    ('cnh', 'Hakha Chin', 'cnh'),
    ('cpy', 'South Ucayali Ashéninka', 'cpy'),
    ('cs', 'Czech', 'ces'),
    ('cte', 'Tepinapa Chinantec', 'cte'),
    ('ctl', 'Tlacoatzintepec Chinantec', 'ctl'),
    ('cut', 'Teutila Cuicatec', 'cut'),
    ('cux', 'Tepeuxila Cuicatec', 'cux'),
    ('cv', 'Chuvash', 'chv'),
    ('cy', 'Welsh', 'cym'),
    ('da', 'Danish', 'dan'),
    ('dag', 'Dagbani', 'dag'),
    ('dar', 'Dargwa', 'dar'),
    ('dav', 'Taita', 'dav'),
    ('dbd', 'Dadiya', 'dbd'),
    ('dcc', 'Deccan', 'dcc'),
    ('de', 'German', 'deu'),
    ('deg', 'Degema', 'deg'),
    ('dgh', 'Dghwede', 'dgh'),
    ('dgo', 'Dogri', 'dgo'),
    ('dje', 'Zarma', 'dje'),
    ('dmk', 'Domaaki', 'dmk'),
    ('dml', 'Dameli', 'dml'),
    ('dru', 'Rukai', 'dru'),
    ('dty', 'Dotyali', 'dty'),
    ('dua', 'Duala', 'dua'),
    ('dv', 'Dhivehi', 'div'),
    ('dyu', 'Dyula', 'dyu'),
    ('dzg', 'Dazaga', 'dzg'),
    ('ebr', 'Ebrié', 'ebr'),
    ('ebu', 'Embu', 'ebu'),
    ('ego', 'Eggon', 'ego'),
    ('eiv', 'Askopan', 'eiv'),
    ('eko', 'Koti', 'eko'),
    ('ekr', 'Yace', 'ekr'),
    ('el', 'Greek', 'ell'),
    ('elm', 'Eleme', 'elm'),
    ('en', 'English', 'eng'),
    ('eo', 'Esperanto', 'epo'),
    ('es', 'Spanish', 'spa'),
    ('esu', 'Central Yupik', 'esu'),
    ('et', 'Estonian', 'est'),
    ('eto', 'Eton (Cameroon)', 'eto'),
    ('ets', 'Yekhee', 'ets'),
    ('etu', 'Ejagham', 'etu'),
    ('eu', 'Basque', 'eus'),
    ('ewo', 'Ewondo', 'ewo'),
    ('ext', 'Extremaduran', 'ext'),
    ('eyo', 'Keiyo', 'eyo'),
    ('fa', 'Persian', 'fas'),
    ('fan', 'Fang (Equatorial Guinea)', 'fan'),
    ('fat', 'Fanti', 'fat'),
    ('ff', 'Fulah', 'ful'),
    ('ffm', 'Maasina Fulfulde', 'ffm'),
    ('fi', 'Finnish', 'fin'),
    ('fia', 'Nobiin', 'fia'),
    ('fil', 'Filipino', 'fil'),
    ('fip', 'Fipa', 'fip'),
    ('fkk', 'Kirya-Konzəl', 'fkk'),
    ('fmp', "Fe'fe'", 'fmp'),
    ('fr', 'French', 'fra'),
    ('fub', 'Adamawa Fulfulde', 'fub'),
    ('fuc', 'Pulaar', 'fuc'),
    ('fue', 'Borgu Fulfulde', 'fue'),
    ('fuf', 'Pular', 'fuf'),
    ('fuh', 'Western Niger Fulfulde', 'fuh'),
    ('fui', 'Bagirmi Fulfulde', 'fui'),
    ('fuq', 'Central-Eastern Niger Fulfulde', 'fuq'),
    ('fuv', 'Nigerian Fulfulde', 'fuv'),
    ('fy', 'Western Frisian', 'fry'),
    ('ga', 'Irish', 'gle'),
    ('gbm', 'Garhwali', 'gbm'),
    ('gbr', 'Gbagyi', 'gbr'),
    ('gby', 'Gbari', 'gby'),
    ('gcc', 'Mali', 'gcc'),
    ('gdf', 'Guduf-Gava', 'gdf'),
    ('gej', 'Gen', 'gej'),
    ('ges', 'Geser-Gorom', 'ges'),
    ('ggg', 'Gurgula', 'ggg'),
    ('gid', 'Gidar', 'gid'),
    ('gig', 'Goaria', 'gig'),
    ('giz', 'South Giziga', 'giz'),
    ('gjk', 'Kachi Koli', 'gjk'),
    ('gju', 'Gujari', 'gju'),
    ('gl', 'Galician', 'glg'),
    ('glw', 'Glavda', 'glw'),
    ('gn', 'Guarani', 'grn'),
    ('gol', 'Gola', 'gol'),
    ('gom', 'Goan Konkani', 'gom'),
    ('gsl', 'Gusilay', 'gsl'),
    ('gu', 'Gujarati', 'guj'),
    ('gui', 'Eastern Bolivian Guaraní', 'gui'),
    ('gur', 'Farefare', 'gur'),
    ('guz', 'Gusii', 'guz'),
    ('gv', 'Manx', 'glv'),
    ('gwc', 'Gawri', 'gwc'),
    ('gwe', 'Gweno', 'gwe'),
    ('gwt', 'Gawar-Bati', 'gwt'),
    ('gya', 'Northwest Gbaya', 'gya'),
    ('gyz', 'Geji', 'gyz'),
    ('ha', 'Hausa', 'hau'),
    ('hah', 'Hahon', 'hah'),
    ('hao', 'Hakö', 'hao'),
    ('haw', 'Hawaiian', 'haw'),
    ('haz', 'Hazaragi', 'haz'),
    ('hbb', 'Huba', 'hbb'),
    ('he', 'Hebrew', 'heb'),
    ('hem', 'Hemba', 'hem'),
    ('hi', 'Hindi', 'hin'),
    ('hia', 'Lamang', 'hia'),
    ('hkk', 'Hunjara-Kaina Ke', 'hkk'),
    ('hla', 'Halia', 'hla'),
    ('hno', 'Northern Hindko', 'hno'),
    ('hoj', 'Hadothi', 'hoj'),
    ('hr', 'Croatian', 'hrv'),
    ('hsb', 'Upper Sorbian', 'hsb'),
    ('ht', 'Haitian', 'hat'),
    ('hu', 'Hungarian', 'hun'),
    ('hue', 'San Francisco Del Mar Huave', 'hue'),
    ('hul', 'Hula', 'hul'),
    ('hux', 'Nüpode Huitoto', 'hux'),
    ('hwo', 'Hwana', 'hwo'),
    ('hy', 'Armenian', 'hye'),
    ('hz', 'Herero', 'her'),
    ('ia', 'Interlingua (International Auxiliary Language Association)', 'ina'),
    ('ibb', 'Ibibio', 'ibb'),
    ('id', 'Indonesian', 'ind'),
    ('ida', 'Idakho-Isukha-Tiriki', 'ida'),
    ('idu', 'Idoma', 'idu'),
    ('ig', 'Igbo', 'ibo'),
    ('ijc', 'Izon', 'ijc'),
    ('ijn', 'Kalabari', 'ijn'),
    ('ik', 'Inupiaq', 'ipk'),
    ('ikw', 'Ikwere', 'ikw'),
    ('is', 'Icelandic', 'isl'),
    ('ish', 'Esan', 'ish'),
    ('iso', 'Isoko', 'iso'),
    ('it', 'Italian', 'ita'),
    ('its', 'Isekiri', 'its'),
    ('itw', 'Ito', 'itw'),
    ('itz', 'Itzá', 'itz'),
    ('ja', 'Japanese', 'jpn'),
    ('jal', 'Yalahatan', 'jal'),
    ('jax', 'Jambi Malay', 'jax'),
    ('jgo', 'Ngomba', 'jgo'),
    ('jmx', 'Western Juxtlahuaca Mixtec', 'jmx'),
    ('jns', 'Jaunsari', 'jns'),
    ('jqr', 'Jaqaru', 'jqr'),
    ('juk', 'Wapan', 'juk'),
    ('juo', 'Jiba', 'juo'),
    ('jv', 'Javanese', 'jav'),
    ('ka', 'Georgian', 'kat'),
    ('kab', 'Kabyle', 'kab'),
    ('kai', 'Karekare', 'kai'),
    ('kaj', 'Jju', 'kaj'),
    ('kam', 'Kamba', 'kam'),
    ('kbd', 'Kabardian', 'kbd'),
    ('kbl', 'Kanembu', 'kbl'),
    ('kbt', 'Abadi', 'kbt'),
    ('kcq', 'Kamo', 'kcq'),
    ('kdh', 'Tem', 'kdh'),
    ('kea', 'Kabuverdianu', 'kea'),
    ('keu', 'Akebu', 'keu'),
    ('kfe', 'Kota (India)', 'kfe'),
    ('kfk', 'Kinnauri', 'kfk'),
    ('kfp', 'Korwa', 'kfp'),
    ('khg', 'Khams Tibetan', 'khg'),
    ('khw', 'Khowar', 'khw'),
    ('kj', 'Kuanyama', 'kua'),
    ('kjc', 'Coastal Konjo', 'kjc'),
    ('kjk', 'Highland Konjo', 'kjk'),
    ('kk', 'Kazakh', 'kaz'),
    ('kln', 'Kalenjin', 'kln'),
    ('kls', 'Kalasha', 'kls'),
    ('km', 'Khmer', 'khm'),
    ('kmr', 'Northern Kurdish', 'kmr'),
    ('kmy', 'Koma', 'kmy'),
    ('kn', 'Kannada', 'kan'),
    ('kna', 'Dera (Nigeria)', 'kna'),
    ('knn', 'Konkani', 'knn'),
    ('ko', 'Korean', 'kor'),
    ('kol', 'Kol (Papua New Guinea)', 'kol'),
    ('koo', 'Konzo', 'koo'),
    ('kpo', 'Ikposo', 'kpo'),
    ('kqo', 'Eastern Krahn', 'kqo'),
    ('ks', 'Kashmiri', 'kas'),
    ('ksd', 'Kuanua', 'ksd'),
    ('ksf', 'Bafia', 'ksf'),
    ('kto', 'Kuot', 'kto'),
    ('kuh', 'Kushi', 'kuh'),
    ('kvx', 'Parkari Koli', 'kvx'),
    ('kw', 'Cornish', 'cor'),
    ('kwm', 'Kwambi', 'kwm'),
    ('kxp', 'Wadiyara Koli', 'kxp'),
    ('ky', 'Kirghiz', 'kir'),
    ('kyx', 'Rapoisi', 'kyx'),
    ('lag', 'Rangi', 'lag'),
    ('lb', 'Luxembourgish', 'ltz'),
    ('lcm', 'Tungag', 'lcm'),
    ('ldb', 'Dũya', 'ldb'),
    ('lg', 'Ganda', 'lug'),
    ('lij', 'Ligurian', 'lij'),
    ('lir', 'Liberian English', 'lir'),
    ('lkb', 'Kabras', 'lkb'),
    ('lla', 'Lala-Roba', 'lla'),
    ('ln', 'Lingala', 'lin'),
    ('lnu', 'Longuda', 'lnu'),
    ('lo', 'Lao', 'lao'),
    ('loa', 'Loloda', 'loa'),
    ('lrk', 'Loarki', 'lrk'),
    ('lss', 'Lasi', 'lss'),
    ('lt', 'Lithuanian', 'lit'),
    ('ltg', 'Latgalian', 'ltg'),
    ('lto', 'Tsotso', 'lto'),
    ('lua', 'Luba-Lulua', 'lua'),
    ('luo', 'Luo', 'luo'),
    ('lus', 'Lushai', 'lus'),
    ('lv', 'Latvian', 'lav'),
    ('lwg', 'Wanga', 'lwg'),
    ('mab', 'Yutanduchi Mixtec', 'mab'),
    ('maf', 'Mafa', 'maf'),
    ('mai', 'Maithili', 'mai'),
    ('mau', 'Huautla Mazatec', 'mau'),
    ('max', 'North Moluccan Malay', 'max'),
    ('mbo', 'Mbo (Cameroon)', 'mbo'),
    ('mcf', 'Matsés', 'mcf'),
    ('mcn', 'Masana', 'mcn'),
    ('mcx', 'Mpiemo', 'mcx'),
    ('mdd', 'Mbum', 'mdd'),
    ('mde', 'Maba (Chad)', 'mde'),
    ('mdf', 'Moksha', 'mdf'),
    ('mek', 'Mekeo', 'mek'),
    ('mer', 'Meru', 'mer'),
    ('meu', 'Motu', 'meu'),
    ('mfm', 'Marghi South', 'mfm'),
    ('mfn', 'Cross River Mbembe', 'mfn'),
    ('mfo', 'Mbe', 'mfo'),
    ('mfv', 'Mandjak', 'mfv'),
    ('mgg', 'Mpumpong', 'mgg'),
    ('mgi', 'Lijili', 'mgi'),
    ('mhk', 'Mungaka', 'mhk'),
    ('mhr', 'Eastern Mari', 'mhr'),
    ('mi', 'Maori', 'mri'),
    ('mig', 'San Miguel El Grande Mixtec', 'mig'),
    ('miu', 'Cacaloxtepec Mixtec', 'miu'),
    ('mk', 'Macedonian', 'mkd'),
    ('mkf', 'Miya', 'mkf'),
    ('mki', 'Dhatki', 'mki'),
    ('ml', 'Malayalam', 'mal'),
    ('mlq', 'Western Maninkakan', 'mlq'),
    ('mn', 'Mongolian', 'mon'),
    ('mne', 'Naba', 'mne'),
    ('mni', 'Manipuri', 'mni'),
    ('mqy', 'Manggarai', 'mqy'),
    ('mr', 'Marathi', 'mar'),
    ('mrj', 'Western Mari', 'mrj'),
    ('mrr', 'Maria (India)', 'mrr'),
    ('mrt', 'Marghi Central', 'mrt'),
    ('ms', 'Malay', 'msa'),
    ('mse', 'Musey', 'mse'),
    ('msh', 'Masikoro Malagasy', 'msh'),
    ('msw', 'Mansoanka', 'msw'),
    ('mt', 'Maltese', 'mlt'),
    ('mtr', 'Mewari', 'mtr'),
    ('mtu', 'Tututepec Mixtec', 'mtu'),
    ('mtx', 'Tidaá Mixtec', 'mtx'),
    ('mua', 'Mundang', 'mua'),
    ('mug', 'Musgu', 'mug'),
    ('mui', 'Musi', 'mui'),
    ('mve', 'Marwari (Pakistan)', 'mve'),
    ('mvy', 'Indus Kohistani', 'mvy'),
    ('mxs', 'Huitepec Mixtec', 'mxs'),
    ('mxu', 'Mada (Cameroon)', 'mxu'),
    ('mxy', 'Southeastern Nochixtlán Mixtec', 'mxy'),
    ('my', 'Burmese', 'mya'),
    ('myv', 'Erzya', 'myv'),
    ('mzl', 'Mazatlán Mixe', 'mzl'),
    ('nal', 'Nalik', 'nal'),
    ('nan', 'Min Nan Chinese', 'nan'),
    ('nap', 'Neapolitan', 'nap'),
    ('nb', 'Norwegian Bokmål', 'nob'),
    ('nbh', 'Ngamo', 'nbh'),
    ('ncf', 'Notsi', 'ncf'),
    ('nco', 'Sibe', 'nco'),
    ('ncx', 'Central Puebla Nahuatl', 'ncx'),
    ('ndi', 'Samba Leko', 'ndi'),
    ('ng', 'Ndonga', 'ndo'),
    ('ngi', 'Ngizim', 'ngi'),
    ('nhg', 'Tetelcingo Nahuatl', 'nhg'),
    ('nhi', 'Zacatlán-Ahuacatlán-Tepetzintla Nahuatl', 'nhi'),
    ('nhn', 'Central Nahuatl', 'nhn'),
    ('nhq', 'Huaxcaleca Nahuatl', 'nhq'),
    ('nja', 'Nzanyi', 'nja'),
    ('nl', 'Dutch', 'nld'),
    ('nla', 'Ngombale', 'nla'),
    ('nlv', 'Orizaba Nahuatl', 'nlv'),
    ('nmg', 'Kwasio', 'nmg'),
    ('nmz', 'Nawdm', 'nmz'),
    ('nn', 'Norwegian Nynorsk', 'nno'),
    ('nnh', 'Ngiemboon', 'nnh'),
    ('no', 'Norwegian', 'nor'),
    ('noe', 'Nimadi', 'noe'),
    ('npi', 'Nepali', 'npi'),
    ('nso', 'Pedi', 'nso'),
    ('ny', 'Chichewa', 'nya'),
    ('nyu', 'Nyungwe', 'nyu'),
    ('oc', 'Occitan', 'oci'),
    ('odk', 'Od', 'odk'),
    ('odu', 'Odual', 'odu'),
    ('ogo', 'Khana', 'ogo'),
    ('om', 'Oromo', 'orm'),
    ('orc', 'Orma', 'orc'),
    ('oru', 'Ormuri', 'oru'),
    ('ory', 'Odia', 'ory'),
    ('os', 'Iron Ossetic', 'oss'),
    ('pa', 'Panjabi', 'pan'),
    ('pbs', 'Central Pame', 'pbs'),
    ('pbt', 'Southern Pashto', 'pbt'),
    ('pbu', 'Northern Pashto', 'pbu'),
    ('pcm', 'Nigerian Pidgin', 'pcm'),
    ('pex', 'Petats', 'pex'),
    ('phl', 'Phalura', 'phl'),
    ('phr', 'Pahari-Potwari', 'phr'),
    ('pip', 'Pero', 'pip'),
    ('piy', 'Piya-Kwonci', 'piy'),
    ('pko', 'Pökoot', 'pko'),
    ('pl', 'Polish', 'pol'),
    ('plk', 'Kohistani Shina', 'plk'),
    ('plt', 'Plateau Malagasy', 'plt'),
    ('pmq', 'Northern Pame', 'pmq'),
    ('pms', 'Piemontese', 'pms'),
    ('pmy', 'Papuan Malay', 'pmy'),
    ('pnb', 'Western Panjabi', 'pnb'),
    ('poc', 'Poqomam', 'poc'),
    ('poe', 'San Juan Atzingo Popoloca', 'poe'),
    ('pow', 'San Felipe Otlaltepec Popoloca', 'pow'),
    ('prq', 'Ashéninka Perené', 'prq'),
    ('ps', 'Pushto', 'pus'),
    ('pst', 'Central Pashto', 'pst'),
    ('pt', 'Portuguese', 'por'),
    ('pua', 'Western Highland Purepecha', 'pua'),
    ('pwn', 'Paiwan', 'pwn'),
    ('qug', 'Chimborazo Highland Quichua', 'qug'),
    ('qum', 'Sipacapense', 'qum'),
    ('qup', 'Southern Pastaza Quechua', 'qup'),
    ('qur', 'Yanahuanca Pasco Quechua', 'qur'),
    ('qus', 'Santiago del Estero Quichua', 'qus'),
    ('quv', 'Sacapulteco', 'quv'),
    ('qux', 'Yauyos Quechua', 'qux'),
    ('quy', 'Ayacucho Quechua', 'quy'),
    ('qva', 'Ambo-Pasco Quechua', 'qva'),
    ('qvi', 'Imbabura Highland Quichua', 'qvi'),
    ('qvj', 'Loja Highland Quichua', 'qvj'),
    ('qvl', 'Cajatambo North Lima Quechua', 'qvl'),
    ('qwa', 'Corongo Ancash Quechua', 'qwa'),
    ('qws', 'Sihuas Ancash Quechua', 'qws'),
    ('qxa', 'Chiquián Ancash Quechua', 'qxa'),
    ('qxp', 'Puno Quechua', 'qxp'),
    ('qxt', 'Santa Ana de Tusi Pasco Quechua', 'qxt'),
    ('qxu', 'Arequipa-La Unión Quechua', 'qxu'),
    ('qxw', 'Jauja Wanca Quechua', 'qxw'),
    ('rag', 'Logooli', 'rag'),
    ('rm', 'Romansh', 'roh'),
    ('ro', 'Romanian', 'ron'),
    ('rob', "Tae'", 'rob'),
    ('rof', 'Rombo', 'rof'),
    ('roo', 'Rotokas', 'roo'),
    ('rth', 'Ratahan', 'rth'),
    ('ru', 'Russian', 'rus'),
    ('rup', 'Macedo-Romanian', 'rup'),
    ('rw', 'Kinyarwanda', 'kin'),
    ('sa', 'Sanskrit', 'san'),
    ('sah', 'Yakut', 'sah'),
    ('sat', 'Santali', 'sat'),
    ('sau', 'Saleman', 'sau'),
    ('say', 'Saya', 'say'),
    ('sbn', 'Sindhi Bhil', 'sbn'),
    ('sc', 'Sardinian', 'srd'),
    ('scl', 'Shina', 'scl'),
    ('scn', 'Sicilian', 'scn'),
    ('sd', 'Sindhi', 'snd'),
    ('sei', 'Seri', 'sei'),
    ('shu', 'Chadian Arabic', 'shu'),
    ('si', 'Sinhala', 'sin'),
    ('sip', 'Sikkimese', 'sip'),
    ('siw', 'Siwai', 'siw'),
    ('sjr', 'Siar-Lak', 'sjr'),
    ('sk', 'Slovak', 'slk'),
    ('skg', 'Sakalava Malagasy', 'skg'),
    ('skr', 'Saraiki', 'skr'),
    ('sl', 'Slovenian', 'slv'),
    ('sn', 'Shona', 'sna'),
    ('snc', 'Sinaugoro', 'snc'),
    ('snk', 'Soninke', 'snk'),
    ('so', 'Somali', 'som'),
    ('sol', 'Solos', 'sol'),
    ('sps', 'Saposa', 'sps'),
    ('sq', 'Albanian', 'sqi'),
    ('sr', 'Serbian', 'srp'),
    ('src', 'Logudorese Sardinian', 'src'),
    ('sro', 'Campidanese Sardinian', 'sro'),
    ('ssi', 'Sansi', 'ssi'),
    ('ste', 'Liana-Seti', 'ste'),
    ('sua', 'Sulka', 'sua'),
    ('sv', 'Swedish', 'swe'),
    ('sva', 'Svan', 'sva'),
    ('sw', 'Swahili', 'swa'),
    ('szy', 'Sakizaya', 'szy'),
    ('ta', 'Tamil', 'tam'),
    ('tan', 'Tangale', 'tan'),
    ('tar', 'Central Tarahumara', 'tar'),
    ('tay', 'Atayal', 'tay'),
    ('tbf', 'Mandara', 'tbf'),
    ('tcf', "Malinaltepec Me'phaa", 'tcf'),
    ('tcy', 'Tulu', 'tcy'),
    ('tdn', 'Tondano', 'tdn'),
    ('tdx', 'Tandroy-Mahafaly Malagasy', 'tdx'),
    ('te', 'Telugu', 'tel'),
    ('tg', 'Tajik', 'tgk'),
    ('tgc', 'Tigak', 'tgc'),
    ('th', 'Thai', 'tha'),
    ('the', 'Chitwania Tharu', 'the'),
    ('thq', 'Kochila Tharu', 'thq'),
    ('thr', 'Rana Tharu', 'thr'),
    ('thv', 'Tahaggart Tamahaq', 'thv'),
    ('ti', 'Tigrinya', 'tir'),
    ('tig', 'Tigre', 'tig'),
    ('tio', 'Teop', 'tio'),
    ('tk', 'Turkmen', 'tuk'),
    ('tkg', 'Tesaka Malagasy', 'tkg'),
    ('tkt', 'Kathoriya Tharu', 'tkt'),
    ('tli', 'Tlingit', 'tli'),
    ('tlp', 'Filomena Mata-Coahuitlán Totonac', 'tlp'),
    ('tn', 'Tswana', 'tsn'),
    ('tok', 'Toki Pona', 'tok'),
    ('tpl', "Tlacoapa Me'phaa", 'tpl'),
    ('tpz', 'Tinputz', 'tpz'),
    ('tqp', 'Tomoip', 'tqp'),
    ('tr', 'Turkish', 'tur'),
    ('trp', 'Kok Borok', 'trp'),
    ('trq', 'San Martín Itunyoso Triqui', 'trq'),
    ('trv', 'Sediq', 'trv'),
    ('trw', 'Torwali', 'trw'),
    ('tt', 'Tatar', 'tat'),
    ('ttj', 'Tooro', 'ttj'),
    ('ttr', 'Tera', 'ttr'),
    ('ttu', 'Torau', 'ttu'),
    ('tui', 'Tupuri', 'tui'),
    ('tul', 'Tula', 'tul'),
    ('tuq', 'Tedaga', 'tuq'),
    ('tuv', 'Turkana', 'tuv'),
    ('tuy', 'Tugen', 'tuy'),
    ('tvo', 'Tidore', 'tvo'),
    ('tvu', 'Tunen', 'tvu'),
    ('tw', 'Twi', 'twi'),
    ('twu', 'Termanu', 'twu'),
    ('txs', 'Tonsea', 'txs'),
    ('txy', 'Tanosy Malagasy', 'txy'),
    ('udl', 'Wuzlam', 'udl'),
    ('ug', 'Uighur', 'uig'),
    ('uk', 'Ukrainian', 'ukr'),
    ('uki', 'Kui (India)', 'uki'),
    ('umb', 'Umbundu', 'umb'),
    ('ur', 'Urdu', 'urd'),
    ('ush', 'Ushojo', 'ush'),
    ('uz', 'Uzbek', 'uzb'),
    ('uzn', 'Northern Uzbek', 'uzn'),
    ('vai', 'Vai', 'vai'),
    ('var', 'Huarijio', 'var'),
    ('ver', 'Mom Jango', 'ver'),
    ('vi', 'Vietnamese', 'vie'),
    ('vmc', 'Juxtlahuaca Mixtec', 'vmc'),
    ('vmj', 'Ixtayutla Mixtec', 'vmj'),
    ('vmm', 'Mitlatongo Mixtec', 'vmm'),
    ('vmp', 'Soyaltepec Mazatec', 'vmp'),
    ('vmz', 'Mazatlán Mazatec', 'vmz'),
    ('vot', 'Votic', 'vot'),
    ('vro', 'Võro', 'vro'),
    ('wbl', 'Wakhi', 'wbl'),
    ('wci', 'Waci Gbe', 'wci'),
    ('weo', 'Wemale', 'weo'),
    ('wes', 'Cameroon Pidgin', 'wes'),
    ('wja', 'Waja', 'wja'),
    ('wji', 'Warji', 'wji'),
    ('wo', 'Wolof', 'wol'),
    ('wof', 'Gambian Wolof', 'wof'),
    ('xh', 'Xhosa', 'xho'),
    ('xhe', 'Khetrani', 'xhe'),
    ('xka', 'Kalkoti', 'xka'),
    ('xmf', 'Mingrelian', 'xmf'),
    ('xmv', 'Antankarana Malagasy', 'xmv'),
    ('xmw', 'Tsimihety Malagasy', 'xmw'),
    ('xpe', 'Liberia Kpelle', 'xpe'),
    ('xti', 'Sinicahua Mixtec', 'xti'),
    ('xtu', 'Cuyamecalco Mixtec', 'xtu'),
    ('yaq', 'Yaqui', 'yaq'),
    ('yav', 'Yangben', 'yav'),
    ('yay', 'Agwagwune', 'yay'),
    ('ydd', 'Eastern Yiddish', 'ydd'),
    ('ydg', 'Yidgha', 'ydg'),
    ('yer', 'Tarok', 'yer'),
    ('yes', 'Nyankpa', 'yes'),
    ('yi', 'Yiddish', 'yid'),
    ('yo', 'Yoruba', 'yor'),
    ('yue', 'Cantonese', 'yue'),
    ('zga', 'Kinga', 'zga'),
    ('zgh', 'Standard Moroccan Tamazight', 'zgh'),
    ('zh', 'Chinese', 'cmn'),
    ('zoc', 'Copainalá Zoque', 'zoc'),
    ('zoh', 'Chimalapa Zoque', 'zoh'),
    ('zor', 'Rayón Zoque', 'zor'),
    ('zpv', 'Chichicapan Zapotec', 'zpv'),
    ('zpy', 'Mazaltepec Zapotec', 'zpy'),
    ('ztg', 'Xanaguía Zapotec', 'ztg'),
    ('ztn', 'Santa Catarina Albarradas Zapotec', 'ztn'),
    ('ztp', 'Loxicha Zapotec', 'ztp'),
    ('zts', 'Tilquiapan Zapotec', 'zts'),
    ('ztu', 'Güilá Zapotec', 'ztu'),
    ('zu', 'Zulu', 'zul'),
    ('zza', 'Zaza', 'zza'),
)
